# Generated by Django 4.1.5 on 2023-01-14 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='profile_image_url',
        ),
    ]
