# Generated by Django 4.1.5 on 2023-01-24 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapi', '0002_rename_password_user_profile_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productonorder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='galleryapi.order'),
        ),
    ]
