# Generated by Django 4.1.5 on 2023-01-24 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapi', '0003_alter_productonorder_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productonorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='galleryapi.order'),
        ),
    ]
